services:
  shopco_nest:
    build: .
    container_name: shopco_nest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5008
      - DB_NAME=shopco_postgres
      - DB_USER=postgres
      - DB_PASSWORD=WkBME5bdzrNtagqjuvLs
      - DB_HOST=shopco_postgres
      - DB_PORT=5432
      - JWT_SECRET=c5FEEWoti8rjAYNaULGB
      - JWT_REFRESH_SECRET=QqbjYfXnf60B5rQkVXyW
    ports:
      - '5001:5001'
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - shopco_postgres

  shopco_postgres:
    image: postgres:18-alpine
    container_name: shopco_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopco_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WkBME5bdzrNtagqjuvLs
    ports:
      - '5433:5432'
    volumes:
      - shop_postgres_data:/var/lib/postgresql/data

volumes:
  shop_postgres_data:
